### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by alexpls** [jaanus/UICollectionView-separator#1]
The link to your blog in the Readme file is broken, I was keen to see your comments on implementing this separator. I tried to find the article by going through the archive, but no luck :cry:

**Comment by jaanus** [comment]
Whoops. Thank you for pointing this out. Some blog posts had gone missing. Good thing I kept those in version control as well. Fixed now.

**Comment by alexpls** [comment]
Thanks for that, great blog post by the way!
